### ISSUE TITLE
잘못된 Author 링크

### ISSUE THREAD

**Issue by onsemy** [balancehero/kinsumer#1]
![1508135595368](https://user-images.githubusercontent.com/2973238/31598283-ba91712e-b287-11e7-88eb-770e1289b41d.jpg)

README.md에서 작성자(Ungi Kim)의 링크가 잘못 표기되어 있는 것 같습니다.
https://ungimim.me -> https://ungikim.me

**Comment by ungikim** [comment]
수정했습니다.
